### PR TITLE
Move tests into fc25 environment

### PR DESCRIPTION
**Pull request by j-mracek**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
if it works -- totally fine with me ;)

**Comment by ignatenkobrain** [comment]
@MichaelMraka you know that you will need to update environment by jenkins-jobs, right? ;)

**Comment by MichaelMraka** [comment]
@ignatenkobrain Umm, no :(. I'm afraid I don't even have an access.

**Comment by ignatenkobrain** [comment]
@MichaelMraka you do have ;)

**Comment by j-mracek** [comment]
@ignatenkobrain @MichaelMraka I do that right now

**Pull request merged**
