### PR TITLE
Dnf5 support

### PR DESCRIPTION
**Pull request by lukash**
This adds support for running scenarios marked with the `@dnf5` tag in "dnf5 mode", which is stored in DNFContext and allows to conditionally handle differences between dnf4 and dnf5 in behave steps.

### CODE REVIEW

**Comment by dmach** [comment]
@lukash it would be good to replace <REPOSYNC> with something a bit less misleading (reposync is also a dnf command).
Maybe <REPODATA_SYNC> would be a better choice.

**Comment by m-blaha** [comment]
Let's rather leave this to a separate PR. The change would be needed in lot of files and is kind of unrelated to this PR.

**Comment by lukash** [comment]
@dmach I'm not opposed, but yeah, it's in a lot of places, separately might be better.

**Comment by inknos** [comment]
I agree with your considerations and since the PR looks good to me, and I would need it to push more changes related to the daemon, I would merge it. However, what is the issue with the failing test?

About createrepo_c
```
  createrepo_c/zchunk.feature:76  create repository with zck metadata usign dictionaries
  createrepo_c/zchunk.feature:125  create repository with zck and dictionary metadata with bad package
```
The scenarios are not related. So, what should we do?

**Comment by kontura** [comment]
@inknos we can ignore the createrepo_c tests, its a zchunk issue.

**Comment by dmach** [comment]
FYI: This should help with easier parsing the transaction table, making it similar to DNF 4: https://github.com/rpm-software-management/libdnf/pull/1254

**Pull request merged**
