### PR TITLE
Change expected output in protected_packages test

### PR DESCRIPTION
**Pull request by j-mracek**
The upstream changes changed format of error messages

### CODE REVIEW

**Comment by j-mracek** [comment]
@ignatenkobrain This pull request doesn't solve the problem, please can you help? 
There is still assertion error, but I don't know how to solve it. Please can you help?
```
 Assertion Failed: u'Error: 
       Problem: The operation would result in removing the following protec [truncated]... != u'Error:\n  Problem: The operation would result in removing the following prote [truncated]...
      - Error: 
      -  Problem: The operation would result in removing the following protected packages: TestA
      + Error:
        Problem: The operation would result in removing the following protected packages: TestA
      ? +++++++++

```

**Comment by ignatenkobrain** [comment]
@j-mracek `\n` is basically new line, so you should make a new line in feature file ;)

**Comment by j-mracek** [comment]
@ignatenkobrain The problem is in white space. All white spaces are removed from feature file before 
Problem: The operation

**Comment by ignatenkobrain** [comment]
```diff
diff --git a/dnf-docker-test/features/protected_packages.feature b/dnf-docker-test/features/protected_packages.feature
index 0ec6a0a..10093ca 100644
--- a/dnf-docker-test/features/protected_packages.feature
+++ b/dnf-docker-test/features/protected_packages.feature
@@ -19,7 +19,8 @@ Feature: Protected packages
        Then the command should fail
         And the command stderr should match exactly
             """
-            Error: The operation would result in removing the following protected packages: TestA
+            Error: 
+             Problem: The operation would result in removing the following protected packages: TestA
 
             """
         And rpmdb does not change
@@ -42,7 +43,8 @@ Feature: Protected packages
        Then the command should fail
         And the command stderr should match exactly
             """
-            Error: The operation would result in removing the following protected packages: dnf
+            Error: 
+             Problem: The operation would result in removing the following protected packages: dnf
 
             """
         And rpmdb does not change
@@ -57,7 +59,8 @@ Feature: Protected packages
        Then the command should fail
         And the command stderr should match exactly
             """
-            Error: The operation would result in removing the following protected packages: TestA
+            Error: 
+             Problem: The operation would result in removing the following protected packages: TestA
 
             """
         And rpmdb does not change
```

there's extra space after `Error:`, IMO it doesn't make sense and should be fixed in dnf

**Comment by ignatenkobrain** [comment]
I've fixed it in a bit different way yesterday, so closing.

**Pull request closed without merging**
