### PR TITLE
Debug output enhancement and some cleanups

### PR DESCRIPTION
**Pull request by lukash**
Some debugging enhancements that print the last called command and its outputs in a consistent way and with colors, temp directories handling enhancements and some cleanups.

The last commit also shortens the name of the `dnf-ci-fedora-modular-updates` repository across all tests. The name is too long and triggers a bug with dnf output, which had to be workarounded in one scenario. This change is in order to be able to work with the repositories in a uniform way, without a workaround.

### CODE REVIEW

**Comment by pkratoch** [comment]
Looks good, just one note: In the commit "steps: Print preserved temporary directories", the commit message contains "we print the directories only if we would indeed be deleting them", but it's the other way around.

**Comment by pkratoch** [comment]
@rh-atomic-bot try

**Comment by lukash** [comment]
> Looks good, just one note: In the commit "steps: Print preserved temporary directories", the commit message contains "we print the directories only if we would indeed be deleting them", but it's the other way around.

Well, the whole paragraph is there to note we are moving around the conditions for deletion because of the messages. And this sentence says "would be deleting them", but we aren't deleting them, and those are exactly the conditions under which we want to print the notice... I think it's logically correct, but may be hard to understand :slightly_smiling_face:

**Comment by pkratoch** [comment]
> Well, the whole paragraph is there to note we are moving around the conditions for deletion because of the messages. And this sentence says "would be deleting them", but we aren't deleting them, and those are exactly the conditions under which we want to print the notice... I think it's logically correct, but may be hard to understand slightly_smiling_face

Ok, it's a bit confusing, but I get what you meant and it makes sense.

The rh-atomic-bot is not in ci-dnf-stack, but I ran the tests locally on Fedora 30 and they are passing, so I'll merge this.

**Pull request merged**
