### PR TITLE
Test update installonly package from lower priority repo

### PR DESCRIPTION
**Pull request by m-blaha**
https://bugzilla.redhat.com/show_bug.cgi?id=1733582

### CODE REVIEW

**Comment by lukash** [comment]
Wow :slightly_smiling_face: do we really need three 7500 lines long files to test this? AFAIK the only thing you need to test installonly package is `Provides: installonlypkg(kernel)` (or something similar). The rest is just noise...

**Comment by m-blaha** [comment]
@lukash: you are right. I've just copied overgrown kernel package from some other repository. I'll strip them down to necessary minimum.

**Comment by lukash** [comment]
@m-blaha strictly speaking, you can strip them even more, as you don't need the `-core` subpackage or the other provides, all you really need is a single package with the one `Provides: installonlypkg(kernel)`.

But if you don't want to tune this further, let me know and I'll merge it as it is.

**Comment by m-blaha** [comment]
Yes, but I did want to keep it close to the real kernel packages.

**Comment by lukash** [comment]
I wouldn't think there's a value in that, it could even hide an issue if the implementation was tied to the kernel package structure more than it should.

Anyway...

**Pull request merged**
