### PR TITLE
Add tests for --providers-of=.. with --installed

### PR DESCRIPTION
**Pull request by kontura**
Requires: https://github.com/rpm-software-management/dnf5/pull/1481

### CODE REVIEW

**Comment by jan-kolarik** [comment]
Can we also explicitly check that `<REPOSYNC>` is not present when using `--installed`?

**Comment by kontura** [comment]
Right I should actually remove it from the `stdout is` step.

Or do you mean something like: stdout doesn't contains "Updating and loading repositories"?

**Comment by jan-kolarik** [comment]
> Right I should actually remove it from the stdout is step.

Yep, this is what I was thinking about.

**Comment by jan-kolarik** [comment]
Thanks!

**Pull request merged**
