### PR TITLE
repolist-1: Added test of new handling of --disablerepo and --enablerepo

### PR DESCRIPTION
**Pull request by stepasm**
strict=false --disablerepo -> warning
strict=false --enablerepo -> warning
strict=true --disablerepo -> warning
strict=true --enablerepo -> error

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1345976

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
1. Would be great to have link to bugreport about this
2. Also link to DNF PR (if already there, otherwise add also to IGNORE_TESTS in jobs)
3. I think it doesn't make sense to test with one repo, it's enough to test without.
4. Probably could be split by Scenarios. Once scenario - one usecase with a bit more description.

**Comment by j-mracek** [comment]
@ignatenkobrain ping

**Comment by ignatenkobrain** [comment]
```
    When I successfully run "dnf repolist --disablerepo=* --setopt=strict=true"  # behave/steps/command_steps.py:32
    Then the command stderr should match exactly                                 # behave/steps/command_steps.py:62
      """
      No repository match: *

      """
      Assertion Failed: u'No repository match: *
      No repositories available
      ' != u'No repository match: *
      '
        No repository match: *
      - No repositories available
```

**Comment by ignatenkobrain** [comment]
I merged fixed (syntax) version with xfail. Please do something about it.

**Pull request closed without merging**
