### PR TITLE
Add new scenario for reposync –delete

### PR DESCRIPTION
**Pull request by j-mracek**
It tests that option --delete removes rpms from target repository that
are not present in remote metadata.

### CODE REVIEW

**Comment by j-mracek** [comment]
@janblazek Please could you make a review and confirm, that it works like expected? This not a direct back-port, because setopt repositories changed names in master.

**Comment by janblazek** [comment]
@j-mracek there are no setopt-2 or setopt-1 repositories available in rhel-8.1.0 branch.
Could you use different testing repositories?

**Comment by j-mracek** [comment]
@janblazek I added the missing repositories by back-porting other test

**Comment by janblazek** [comment]
Thank you, it looks OK now.

**Pull request merged**
