### PR TITLE
Tests for the new groups-manager dnf plugin

### PR DESCRIPTION
**Pull request by m-blaha**
Requires: https://github.com/rpm-software-management/dnf-plugins-core/pull/412

### CODE REVIEW

**Review by lukash — COMMENTED** [review]
Binary file alert! :slightly_smiling_face: I would _really_ like to not have binary files in git. Any change in that is hard to review and in this case makes altering the contents of that comps file more difficult, as you need to re-gzip it. There's already a `create_compressed_file_with()` step in `createrepo_c` tests, so you can move it to `common` and use it in scenario setup to compress the file to the scenario's temporary location. I think it's the best solution.

Can you please add a few tests for basic error handling, like file not found, comps.xml syntax error... possibly others if any of the operations can fail on something (e.g. merging?).

**Comment by m-blaha** [comment]
> Binary file alert! slightly_smiling_face I would _really_ like to not have binary files in git. Any change in that is hard to review and in this case makes altering the contents of that comps file more difficult, as you need to re-gzip it. There's already a `create_compressed_file_with()` step in `createrepo_c` tests, so you can move it to `common` and use it in scenario setup to compress the file to the scenario's temporary location. I think it's the best solution.

:) I was not aware or this step (we should think about creating some kind of a "directory" of existing steps). Makes sense and I will change it.

**Comment by lukash** [comment]
> ... we should think about creating some kind of a "directory" of existing steps ...

You mean in a documentation sense to have an overview? Not sure it's worth the effort unless I'm missing an easy way to do it without making a duplicate list, which would imo just go out of sync. But I agree they're hard to find as they're scattered across files and there even may be some redundancy as a result of that too. But if you have a good idea? :slightly_smiling_face:

**Comment by m-blaha** [comment]
@lukash I was thinking about using Doxygen (or another doc generating tool) and basically generate documentation for steps from docstrings. But it still would require some work - not all steps have those strings.

**Comment by lukash** [comment]
> I was thinking about using Doxygen (or another doc generating tool) and basically generate documentation for steps from docstrings. But it still would require some work - not all steps have those strings.

That could work.. just requires effort to set up and would we then put it up on a webserver somewhere or would people generate it locally...

**Pull request merged**
