### PR TITLE
FAQ: add command to download nightly RPMs

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
ping @rpm-software-management/dnf-team

**Comment by ignatenkobrain** [comment]
last chance, @rpm-software-management/dnf-team

**Comment by jsilhan** [comment]
LGTM. @ignatenkobrain these small kind of improvements in docs should be merged directly without the review - you are just extending documentation so in general the state will always be better that it was before.

**Comment by jsilhan** [comment]
@dnf-bot r+

**Pull request merged**
