### PR TITLE
Replace duplicate tests for yum/dnf name with more general parametrized form

### PR DESCRIPTION
**Pull request by kontura**
Updating the matching of "dnf"/"yum" in output as discussed here: https://github.com/rpm-software-management/ci-dnf-stack/pull/710

### CODE REVIEW

**Comment by lukash** [comment]
Okay, this looks good and thanks for coming back to it.

But as it is, you are removing the yum tests, are we already explicitly running the test suite against yum or does it remain to be implemented?

**Comment by kontura** [comment]
So the original motivation for this was failing gating, it used to fail because it is run with yum on rhel and the outputs expected dnf. The suite can be run with yum using `./dnf-testing run --command yum`.

I agree with your and @m-blaha's comments from #710 that its preferable to be able to run the whole suite with either dnf or yum, rather than to have couple specific scenarios for yum.

**Comment by lukash** [comment]
> So the original motivation for this was failing gating, it used to fail because it is run with yum on rhel and the outputs expected dnf.

Ok, but I seem to recall another reason for the tests was to actually make sure that dnf does say "yum" and not "dnf" in its output if run through the `yum` command. I'm not entirely sure and looking for the commits led me to #710, so maybe I'm misremembering. @j-mracek, you were making the changes, do we need to explicitly test that dnf says "yum" if you use the `yum` symlink or are we good here?

**Comment by j-mracek** [comment]
If there was a test that always used yum prefix it must stay there. YUM prefix is very important for us and functionality must be tested always in upstream.

**Comment by kontura** [comment]
Ok, its no problem, we can keep it as it is.

**Pull request closed without merging**
