### PR TITLE
Run tests in parallel

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
this should reduce time to run tests, because tests will be run in parallel (by number of cores).

**Comment by ignatenkobrain** [comment]
P.S. I didn't tested it

**Comment by jsilhan** [comment]
> P.S. I didn't tested it

Can you test it then if it works, please?

**Comment by ignatenkobrain** [comment]
@jsilhan tried it. So far speed increased from 11-12 mins -> 3-4 mins

**Comment by jsilhan** [comment]
great, if it works then merge it, please.

**Comment by ignatenkobrain** [comment]
merged

**Pull request merged**
