### PR TITLE
Add test for main repoquery functionality

### PR DESCRIPTION
**Pull request by janblazek**
This is a test for dnf repoquery main functionality,
i.e. for options --requires, --provides, --conflicts, --obsoletes,
--whatrequires, --whatprovides, --whatconflicts, --whatobsoletes

### CODE REVIEW

**Comment by kkaarreell** [comment]
Honzo,
would it be possible to make the check more specific, i.e. instead of 
`the command stdout should match regexp "TestB"`
use
`the command stdout should match exactly`?
The output of repoquery should not be complicated and therefore it seems to me better to match whole output.

**Comment by ignatenkobrain** [comment]
Fully agree with @kkaarreell ;)

**Comment by janblazek** [comment]
I have rewritten the test to use the "match exactly".
@kkaarreell , the "Last metadata expiration check" message is written to stderr and I am comparing just the stdout.

**Comment by ignatenkobrain** [comment]
@janblazek could you rebase please?

**Comment by janblazek** [comment]
@ignatenkobrain done.

**Pull request merged**
