### PR TITLE
Add obsoletes test and obsoletes-1 repository

### PR DESCRIPTION
**Pull request by j-mracek**

### CODE REVIEW

**Comment by j-mracek** [comment]
@mluscon Please can you choose someone for review? The tests are related to  merged PR of jsilhan.

**Comment by mluscon** [comment]
Hmm, who merged jsilhan's PR?

**Comment by j-mracek** [comment]
@mluscon Me, but the tests were developed after that.

**Comment by j-mracek** [comment]
@mluscon If you agree I can merge them.

**Comment by mluscon** [comment]
Wouldn't it be better to use on-site repo definition here?

**Comment by j-mracek** [comment]
@mluscon On side repo do not support multiple version of package. If you mean something like:
```
      Given empty repository "TestA"
        And empty repository "TestB"
        And repository "TestC" with packages
         | Package | Tag | Value |
         | TestA   |     |       |
         | TestB   |     |       |
         | TestC   |     |       |
       When I enable repository "TestB"
        And I enable repository "TestC"
```

**Comment by j-mracek** [comment]
Test obsoletes-2 fails due to new issue probably in libsolv. Libsolv behave differently for install and upgrades, where installs prioritize by provides but upgrade by obsoletes. I will write an issue for libsolv.

**Comment by MichaelMraka** [comment]
@dnf-bot r+

**Pull request merged**
