### PR TITLE
Removal of a not-installed group does not fail

### PR DESCRIPTION
**Pull request by m-blaha**
Test for: https://github.com/rpm-software-management/dnf5/issues/917
Requires: https://github.com/rpm-software-management/dnf5/pull/1013

### CODE REVIEW

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1013

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1013

**Review by j-mracek — APPROVED** [review]
LGTM

**Pull request merged**
