### PR TITLE
Update comps-groups scenarios for dnf5

### PR DESCRIPTION
**Pull request by glum23**
Several scenarios have been updated for dnf5. There are still scenarios waiting for clarification and resolution of related issues (comments have been provided).

### CODE REVIEW

**Comment by jan-kolarik** [comment]
Hello @glum23, `Scenario: 'dnf group list -C' works for unprivileged user even when decompressed` could be also enabled for dnf5 as it is after merging the https://github.com/rpm-software-management/dnf5/pull/786.

**Comment by glum23** [comment]
@jan-kolarik, the scenario has been enabled.

**Comment by j-mracek** [comment]
I am sorry but this change cannot be merged because the feature from https://github.com/rpm-software-management/dnf5/pull/786 will be implemented alternatively.

**Comment by jan-kolarik** [comment]
> I am sorry but this change cannot be merged because the feature from [rpm-software-management/dnf5#786](https://github.com/rpm-software-management/dnf5/pull/786) will be implemented alternatively.

I dropped this single test related to cacheonly functionality and added a comment with a reference to related issue.

**Pull request merged**
