### PR TITLE
Installroot and other improvements

### PR DESCRIPTION
**Pull request by j-mracek**
Sorry, but it looks like that original PR was closed

### CODE REVIEW

**Comment by j-mracek** [comment]
@jsilhan @mluscon @ignatenkobrain This pull-request adds new tests and it changes test steps. It was already reviewed and tests that needs dnf/installroot were excluded by already merged commit. It only affect DDT therefore it cannot conflict with Igor's work. Please can we merge it. It is very important for me.

**Comment by ignatenkobrain** [comment]
A lot of changes ;) Generally looks perfect. If it works for you -- feel free to merge :)

**Comment by jsilhan** [comment]
I am fine with that. @mluscon merge this please when CI is ready for DNF-2.0 branching.

**Comment by j-mracek** [comment]
merged

**Comment by j-mracek** [comment]
closed

**Pull request closed without merging**
