### PR TITLE
Tests for rollback of group upgrade transaction rollback

### PR DESCRIPTION
**Pull request by jan-kolarik**
Requires https://github.com/rpm-software-management/dnf/pull/1852.

### CODE REVIEW

**Comment by pkratoch** [comment]
The change allows not only the undo of the history upgrade rollback, but also the redo (so, the sequence of actions is: `dnf group upgrade`, `dnf history undo last`, `dnf history redo last`). It's probably not a common use case, but can you add tests also for that?

**Comment by jan-kolarik** [comment]
@pkratoch Thanks for the feedback. I was thinking about the sequence of actions you proposed - `upgrade`, `undo last`, `redo last` - and I don't understand what the last operation should mean? Intuitively when I do `undo A` I go to the time point before the A and when I want to undo that I will do the A operation again. That's fine and this is working now. But when you want to redo `undo A` it means do nothing, right? :slightly_smiling_face: I've also check the similar sequence: `install package`, `undo last`, `redo last` for a single package with the current DNF version and it doesn't work either.

**Comment by pkratoch** [comment]
> @pkratoch Thanks for the feedback. I was thinking about the sequence of actions you proposed - `upgrade`, `undo last`, `redo last` - and I don't understand what the last operation should mean? Intuitively when I do `undo A` I go to the time point before the A and when I want to undo that I will do the A operation again. That's fine and this is working now. But when you want to redo `undo A` it means "do nothing", right? slightly_smiling_face

Yes, it's not usable in this context, but I imagine you could have scenario where you would want to replicate list of transactions on another system or you'd want to complete saved transaction or something like that (I remember an RFE for this, but I don't know if and how it was implemented at the end). In either case, you don't want to fail with error that the action is unknown (as it was before your patch).

> I've also check the similar sequence: `install package`, `undo last`, `redo last` for a single package with the current DNF version and it doesn't work either.

Hm, I think it works, there is just nothing to do... or did I misunderstand what you meant?
```
# dnf install nano
# dnf history undo last
# dnf history redo last
Last metadata expiration check: 0:00:18 ago on Tue Sep 13 13:16:19 2022.
Dependencies resolved.
Nothing to do.
Complete!
Warning, the following problems occurred while running a transaction:
  Package nevra "nano-6.0-2.fc36.x86_64" not installed for action "Removed".
# echo $?
0
```

**Comment by jan-kolarik** [comment]
@pkratoch Thank you, I understand now :slightly_smiling_face: I will prepare the additional test for that.

> Hm, I think it works, there is just nothing to do... or did I misunderstand what you meant?

You're right, I've just seen the `Warning` there and overlooked that the whole operation exited successfully.

**Pull request merged**
