### PR TITLE
clean and clean-cachefiles: update scenarios for dnf5

### PR DESCRIPTION
**Pull request by glum23**
Scenarios in clean.feature and clean-cachefiles.feature have been updated for dnf5.
One scenario is still not enabled for dnf5 due to -C option which is not implemented in dnf5 yet.

### CODE REVIEW

**Comment by inknos** [comment]
I am having issues with the dnf5 tests locally. I am doing another round today

**Comment by jan-kolarik** [comment]
I was not checking it deeply, but I've also queued some changes related to clean there: https://github.com/rpm-software-management/ci-dnf-stack/pull/1239

**Comment by glum23** [comment]
@jan-kolarik the changes of clean-cachefiles.feature seem to be the same. However, changes are not part of a separate commit either here or in your PR.

**Comment by jan-kolarik** [comment]
You're right. Nevermind, I will eventually rebase my PR, there could be still same changes after the review...

**Pull request merged**
