### PR TITLE
always rebase ci PR to target branch

### PR DESCRIPTION
**Pull request by inknos**

### CODE REVIEW

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Review by m-blaha — APPROVED** [review]

**Pull request merged**
