### PR TITLE
added Conflicts support to SPEC

### PR DESCRIPTION
**Pull request by kkaarreell**
adds an option to specify package Conflicts when building a repo

### CODE REVIEW

**Comment by mluscon** [comment]
Thank you Karel. You can ignore the line length warning, but please remove the trailing whitespace.

**Comment by kkaarreell** [comment]
Trailing whitespaces should be fixed now (btw, I have copied the line above, all of them have trailing whitespaces)

**Comment by ignatenkobrain** [comment]
@kkaarreell put it back ;) documentation should be in pretty-format ;)

**Comment by kkaarreell** [comment]
Should be back again now.

**Pull request merged**
