### PR TITLE
Test config-manager --dump main

### PR DESCRIPTION
**Pull request by pkratoch**
Requires: https://github.com/rpm-software-management/dnf-plugins-core/pull/480

### CODE REVIEW

**Comment by jan-kolarik** [comment]
This should be probably moved to the `dnf-4-stack` branch ...

**Comment by pkratoch** [comment]
Thanks, I forgot we branched. I moved it there :)

**Comment by jan-kolarik** [comment]
Hmm I don't know if it is because of the "move" or because it's the first commit after changing the GitHub workflow for `dnf-4-stack` branch, but it is only triggering the `dnf5` tests instead of just `dnf` one...

**Comment by pkratoch** [comment]
I will try to open the PR again.

**Comment by pkratoch** [comment]
New PR: https://github.com/rpm-software-management/ci-dnf-stack/pull/1225

**Pull request closed without merging**
