### PR TITLE
rhel-9.5.0: Add extended test for installonly packages

### PR DESCRIPTION
**Pull request by ppisar**
Upstream commit: b2a97d200cce0deaeb437f50eced056636d5b415
For: https://github.com/rpm-software-management/dnf/pull/2085
For: https://issues.redhat.com/browse/RHEL-15902

@j-mracek, please review this rhel-9.5.0 backport of your commit for RHEL-15902.

### CODE REVIEW

**Comment by j-mracek** [comment]
The patch requires additional feature
```
You can implement step definitions for undefined steps with these snippets:
@then(u'dnf5 transaction items for transaction "last" are')
def step_impl(context):
    raise NotImplementedError(u'STEP: Then dnf5 transaction items for transaction "last" are')
```

I am looking for a solution.

**Comment by j-mracek** [comment]
The problematic step can be removed, but there is another problem related to libsolv version where a different transaction might  be created.

**Comment by ppisar** [comment]
I removed the ``dnf5 transaction items for transaction`` steps as irrelevant for DNF4.

**Comment by j-mracek** [comment]
LGTM

**Comment by ppisar** [comment]
Thanks for the review. I will merge it after a pull request with the code https://github.com/rpm-software-management/dnf/pull/2085.

**Pull request merged**
