### PR TITLE
Enable provides scenarios

### PR DESCRIPTION
**Pull request by inknos**

### CODE REVIEW

**Comment by inknos** [comment]
/packit tests https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
/packit test https://github.com/rpm-software-management/dnf5/pull/1037

**Comment by inknos** [comment]
@jan-kolarik I am investigating and addressing the tmt issues here https://github.com/rpm-software-management/ci-dnf-stack/pull/1419.

Let's consider just the old ci checks which are green

**Review by jan-kolarik — APPROVED** [review]
LGTM, thanks

**Pull request merged**
