### PR TITLE
Add coverage for improved countme system age (dnf 4)

### PR DESCRIPTION
**Pull request by dmnks**
Tests for https://github.com/rpm-software-management/libdnf/pull/1662.

Rebased from #1501.

### CODE REVIEW

**Comment by jan-kolarik** [comment]
@dmnks I've run the tests after the PR actually being merged, but the countme scenarios are failing there. Could you please take a look?

**Comment by dmnks** [comment]
Hmm, that's weird, will have a closer look later today. Thanks!

**Comment by dmnks** [comment]
OK, this is a test issue. The failing scenario makes the "+3 days" step fall into a new "countme week", probably due to timezone differences. I'm looking into it now.

**Comment by dmnks** [comment]
Should be fixed now. I've made some of these "fixup" commits so you can see the changes but feel free to squash them before merging the PR (or let me know and I'll squash them).

**Comment by dmnks** [comment]
Nevermind, I've squashed them now :smile: It's now ready to be merged as is.

**Review by jan-kolarik — APPROVED** [review]
Thanks!

**Pull request merged**
